# Generated by Django 4.0.2 on 2022-02-26 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='slug',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
