# Generated by Django 4.0.2 on 2022-02-26 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_notes_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'ordering': ('-date_created',)},
        ),
        migrations.AddField(
            model_name='notes',
            name='date',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
