# Generated by Django 4.0.2 on 2022-02-26 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_notes_options_notes_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notes',
            old_name='desciption',
            new_name='description',
        ),
    ]
